name: Launcher Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build launcher
        run: ./gradlew :launcher:build

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          files: launcher/build/libs/cat-client-2-launcher.jar
          generate_release_notes: true
